---
- name: Install nginx
  dnf:
    name: nginx
    state: latest

- name: Copy proxy site
  copy:
    src: proxy.conf
    dest: /etc/nginx/conf.d/proxy.conf
    mode: u=rw,go=r
    owner: root
    group: root

- name: Copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: u=rw,go=r
    owner: root
    group: root

- name: Start nginx
  systemd:
    name: nginx.service
    state: started

- name: Reload nginx configuration
  systemd:
    name: nginx.service
    state: reloaded

- name: Open firewall port
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
