---
- name: Install web root disk mount unit
  copy:
    src: var-www.mount
    dest: /etc/systemd/system/var-www.mount
    owner: root
    group: root
    mode: u=rwx,go=rx
  register: varmountunit

- name: Load the web root disk mount unit
  systemd:
    daemon_reload: yes

- name: Enable the web root disk mount unit
  systemd:
    name: var-www.mount
    enabled: yes
