---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Make systemd aware of docker.service
  systemd:
    daemon_reload: yes

- name: Start Docker
  systemd:
    name: docker.service
    state: started

- name: Install python3-docker for Ansible integration with docker
  apt:
    name: python3-docker
    state: present
